import type { Neuron, Connection } from '../types';

export const sampleNeurons: Neuron[] = [
  {
    id: '1',
    nodeType: 'Concept',
    title: 'React',
    description: 'A JavaScript library for building user interfaces',
    images: [],
    keyPoints: ['Component-based architecture', 'Virtual DOM for performance', 'Declarative UI patterns'],
    confidence: 'Solid',
    position: { x: 0, y: 0, z: 0 },
    createdAt: Date.now(),
    modifiedAt: Date.now(),
  },
  {
    id: '2',
    nodeType: 'Concept',
    title: 'Three.js',
    description: '3D graphics library for the web',
    images: [],
    keyPoints: ['WebGL abstraction', 'Scene graph architecture', 'Lighting and materials'],
    confidence: 'Shaky',
    position: { x: 2, y: 1, z: 0 },
    createdAt: Date.now(),
    modifiedAt: Date.now(),
  },
  {
    id: '3',
    nodeType: 'Concept',
    title: 'TypeScript',
    description: 'Typed superset of JavaScript',
    images: [],
    keyPoints: ['Static type checking', 'Better IDE support', 'Catches errors at compile time'],
    confidence: 'Internalized',
    position: { x: -2, y: -1, z: 0 },
    createdAt: Date.now(),
    modifiedAt: Date.now(),
  },
  {
    id: '4',
    nodeType: 'Principle',
    title: 'Zustand',
    description: 'Small, fast state management',
    images: [],
    keyPoints: ['Minimal boilerplate', 'React hooks based'],
    confidence: 'Solid',
    position: { x: 1, y: -2, z: 0 },
    createdAt: Date.now(),
    modifiedAt: Date.now(),
  },
  {
    id: '5',
    nodeType: 'Question',
    title: 'Vite',
    description: 'Next generation frontend tooling',
    images: [],
    keyPoints: ['Lightning fast HMR', 'ESM-based dev server', 'Optimized production builds'],
    confidence: 'New',
    position: { x: -1, y: 2, z: 0 },
    createdAt: Date.now(),
    modifiedAt: Date.now(),
  },
];

export const sampleConnections: Connection[] = [
  {
    id: 'c1',
    sourceId: '1',
    targetId: '2',
    weight: 0.9,
  },
  {
    id: 'c2',
    sourceId: '1',
    targetId: '3',
    weight: 0.8,
  },
  {
    id: 'c3',
    sourceId: '1',
    targetId: '4',
    weight: 0.7,
  },
  {
    id: 'c4',
    sourceId: '1',
    targetId: '5',
    weight: 0.6,
  },
  {
    id: 'c5',
    sourceId: '3',
    targetId: '4',
    weight: 0.5,
  },
  {
    id: 'c6',
    sourceId: '3',
    targetId: '5',
    weight: 0.4,
  },
];
